# SPDX-License-Identifier: Apache-2.0
"""Small CPU regressions; no serving runtime or CUDA initialization required."""

import importlib.util
from pathlib import Path

import pytest
import torch

ROOT = Path(__file__).resolve().parents[2]
CONTRACT = ROOT / "runtime/pipelines_core/stages/model_specific_stages/minimax_h3"


def _module(name):
    spec = importlib.util.spec_from_file_location(name, CONTRACT / f"{name}.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


schedule = _module("comfy_schedule")
noise = _module("comfy_noise")


def test_pinned_comfy_beta_six_step_golden():
    # Generated by Comfy 187eda8 ModelSamplingAV + beta_scheduler(.6, .6),
    # independently compared using the original executable source functions.
    actual = schedule.comfy_beta_av_sigmas(
        num_steps=6, video_shift=12.0, audio_shift=3.0
    )
    assert actual == {
        "video": [
            1.0,
            0.9917265772819519,
            0.9693593978881836,
            0.9233605265617371,
            0.8206143975257874,
            0.5487077236175537,
            0.0,
        ],
        "audio": [
            1.0,
            0.9677079916000366,
            0.8877553939819336,
            0.750749409198761,
            0.5335049629211426,
            0.23310807347297668,
            0.0,
        ],
    }


@pytest.mark.parametrize("steps", [1, 6, 20, 50, 1100])
def test_endpoints_and_strict_decrease(steps):
    actual = schedule.comfy_beta_av_sigmas(
        num_steps=steps, video_shift=12.0, audio_shift=3.0
    )
    assert len(actual["video"]) == len(actual["audio"])
    for sigmas in actual.values():
        assert sigmas[0] == 1.0 and sigmas[-1] == 0.0
        assert all(a > b for a, b in zip(sigmas, sigmas[1:]))
    # More than 1000 requested steps deduplicate the 1000-entry Comfy table.
    assert len(actual["video"]) <= min(steps + 1, 1001)


@pytest.mark.parametrize("seed", [0, 17, 123456789])
def test_joint_noise_order_and_global_rng_isolation(seed):
    generator = torch.Generator(device="cpu").manual_seed(seed)
    shape = (1, 24, 2, 4, 4)
    expected_video = torch.randn(shape, generator=generator)
    expected_audio = torch.randn((1, 32, 2, 8), generator=generator)
    original_rng = torch.get_rng_state().clone()
    video, audio = noise.comfy_av_initial_noise(seed=seed, video_shape=shape, audio_t=8)
    assert torch.equal(video, expected_video)
    assert torch.equal(audio, expected_audio[0].permute(1, 2, 0).reshape(16, 32))
    assert torch.equal(torch.get_rng_state(), original_rng)


def test_opt_in_only_and_unknown_modes_rejected():
    assert schedule.normalize_sigma_schedule(None) == "native"
    assert noise.normalize_noise_layout(None) == "native"
    with pytest.raises(ValueError):
        schedule.normalize_sigma_schedule("beta57")
    with pytest.raises(ValueError):
        noise.normalize_noise_layout("unknown")


@pytest.mark.parametrize(
    "steps,shift", [(0, 12.0), (True, 12.0), (6, float("nan")), (6, 0.0)]
)
def test_invalid_schedule_fails_before_sampling(steps, shift):
    with pytest.raises(ValueError):
        schedule.comfy_beta_av_sigmas(
            num_steps=steps, video_shift=shift, audio_shift=3.0
        )
